import { useState } from "react";

import { getBaseUrl, resetBaseUrl, setBaseUrl } from "../api/client";
import type { Health } from "../api/types";
import { Banner } from "../components/Banner";

interface Props {
  health: Health | null;
  online: boolean | null;
  onRefresh: () => void;
}

export function SettingsPage({ health, online, onRefresh }: Props) {
  const [url, setUrl] = useState(getBaseUrl());
  const [saved, setSaved] = useState(false);

  function handleSave() {
    setBaseUrl(url);
    setUrl(getBaseUrl());
    setSaved(true);
    onRefresh();
  }

  function handleReset() {
    resetBaseUrl();
    setUrl(getBaseUrl());
    setSaved(true);
    onRefresh();
  }

  return (
    <>
      <header className="page-header">
        <h1>Settings</h1>
        <p className="subtitle">
          Connection and model configuration. Everything except the backend URL is set
          server-side in <code>backend/.env</code>.
        </p>
      </header>

      <div className="card">
        <h2>Backend</h2>
        <p className="muted" style={{ margin: "6px 0 14px" }}>
          Where this UI sends its API calls. Stored in this browser only.
        </p>

        <label className="field-label" htmlFor="backend-url">
          Backend URL
        </label>
        <div className="row">
          <input
            id="backend-url"
            className="input"
            value={url}
            onChange={(e) => {
              setUrl(e.target.value);
              setSaved(false);
            }}
          />
          <button className="btn" onClick={handleSave}>
            Save
          </button>
          <button className="btn secondary" onClick={handleReset}>
            Reset
          </button>
        </div>

        {saved && (
          <div style={{ marginTop: 14 }}>
            <Banner kind="success">Saved. Connection status updated in the sidebar.</Banner>
          </div>
        )}
      </div>

      <div className="card">
        <h2>Status</h2>
        {online === false && (
          <div style={{ marginTop: 12 }}>
            <Banner kind="error">
              Backend unreachable. Start it with:{" "}
              <code>uvicorn main:app --reload --port 8000</code> from{" "}
              <code>omnifind/backend</code>.
            </Banner>
          </div>
        )}

        {health && (
          <dl style={{ margin: "12px 0 0", display: "grid", gap: 10 }}>
            <Row label="Application" value={health.app} />
            <Row label="Environment" value={health.env} />
            <Row
              label="AI answers"
              value={health.ai_enabled ? "Enabled" : "Disabled — no GEMINI_API_KEY set"}
            />
            <Row label="Model" value={health.model} />
          </dl>
        )}
      </div>

      <div className="card">
        <h2>About</h2>
        <p className="muted" style={{ marginTop: 8 }}>
          OmniFind indexes PDF, DOCX and TXT documents plus PNG, JPG and JPEG images.
          Text is embedded with BAAI/bge-small-en-v1.5 and images with OpenCLIP
          ViT-B/32; both land in a single Qdrant collection so results rank together.
          Answers on the Ask page are generated by Gemini from retrieved passages only.
        </p>
      </div>
    </>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="row" style={{ justifyContent: "space-between" }}>
      <dt className="muted">{label}</dt>
      <dd style={{ margin: 0, fontWeight: 500 }}>{value}</dd>
    </div>
  );
}
